DO $$
BEGIN
CREATE TYPE booking_status AS ENUM ('WAITING',
                                        'APPROVED',
                                        'REJECTED',
                                        'CANCELLED',
                                        'COMPLETED');
EXCEPTION
    WHEN duplicate_object THEN
        -- Тип уже существует, продолжаем выполнение
        NULL;
END $$;
--'перевести в нижний регистр'

DO $$
BEGIN
CREATE TYPE request_status AS ENUM ('PENDING',
                                        'RESPONDED',
                                        'CANCELLED',
                                        'COMPLETED');
EXCEPTION
    WHEN duplicate_object THEN
        -- Тип уже существует, продолжаем выполнение
        NULL;
END $$;
--'перевести в нижний регистр'

CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(512) NOT NULL,
CONSTRAINT pk_user PRIMARY KEY (id),
CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests(
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
description VARCHAR(200) NOT NULL,
requester BIGINT NOT NULL,
created TIMESTAMP NOT NULL,
status request_status NOT NULL DEFAULT 'PENDING',
CONSTRAINT pk_request PRIMARY KEY (id),
CONSTRAINT fk_request_user FOREIGN KEY (requester) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
owner_id BIGINT NOT NULL,
request_id BIGINT NOT NULL,
name VARCHAR(255) NOT NULL,
description VARCHAR(200) NOT NULL,
available BOOLEAN NOT NULL,
CONSTRAINT pk_item PRIMARY KEY (id),
CONSTRAINT fk_item_request FOREIGN KEY (request_id) REFERENCES requests(id),
CONSTRAINT fk_item_user FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS request_items(
request_id BIGINT NOT NULL,
item_id BIGINT NOT NULL,
CONSTRAINT pk_request_item PRIMARY KEY (request_id, item_id),
CONSTRAINT fk_request_items_request FOREIGN KEY (request_id) REFERENCES requests(id),
CONSTRAINT fk_request_items_item FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS bookings (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
booker_id BIGINT NOT NULL,
item_id BIGINT NOT NULL,
start TIMESTAMP NOT NULL,
stop TIMESTAMP NOT NULL,
status booking_status NOT NULL DEFAULT 'WAITING',
CONSTRAINT pk_booking PRIMARY KEY (id),
CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) REFERENCES users(id),
CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
booker_id BIGINT NOT NULL,
item_id BIGINT NOT NULL,
comment VARCHAR(512) NOT NULL,
is_task_completed BOOLEAN NOT NULL,
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL,
CONSTRAINT pk_comment PRIMARY KEY (id),
CONSTRAINT fk_comment_user FOREIGN KEY (booker_id) REFERENCES users(id),
CONSTRAINT fk_comment_item FOREIGN KEY (item_id) REFERENCES items(id)
);

 -- Индексы для внешних ключей
 CREATE INDEX IF NOT EXISTS idx_requests_requester ON requests(requester);
 CREATE INDEX IF NOT EXISTS idx_items_request_id ON items(request_id);
 CREATE INDEX IF NOT EXISTS idx_request_items_request_id ON request_items(request_id);
 CREATE INDEX IF NOT EXISTS idx_request_items_item_id ON request_items(item_id);
 CREATE INDEX IF NOT EXISTS idx_bookings_booker_id ON bookings(booker_id);
 CREATE INDEX IF NOT EXISTS idx_bookings_item_id ON bookings(item_id);
 CREATE INDEX IF NOT EXISTS idx_comments_booker_id ON comments(booker_id);
 CREATE INDEX IF NOT EXISTS idx_comments_item_id ON comments(item_id);

 -- Индексы по статусам
 CREATE INDEX IF NOT EXISTS idx_booking_status ON bookings(status);
 CREATE INDEX IF NOT EXISTS idx_request_status ON requests(status);
